In [1]:
import numpy as np

In [ ]:
# task1 creating arrays

In [5]:
arr = np.arange(1,11)

In [9]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
print(arr.shape)

(10,)


In [11]:
print(arr.size)

10


In [12]:
print(arr.dtype)

int64


In [13]:
arr = np.arange(1,10).reshape(3,3)

In [14]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
print(arr.shape)

(3, 3)


In [16]:
print(arr.size)

9


In [17]:
print(arr.dtype)

int64


In [21]:
arr = np.random.rand(3,3,3)

In [22]:
print(arr)

[[[0.19323354 0.34952334 0.49219098]
  [0.73457551 0.1564873  0.53879278]
  [0.31710225 0.95875776 0.64239523]]

 [[0.58255048 0.66023604 0.71581123]
  [0.55886496 0.59768202 0.13800962]
  [0.9080058  0.7295054  0.37461346]]

 [[0.33440204 0.96176654 0.7391097 ]
  [0.49290588 0.23977472 0.5813377 ]
  [0.74293358 0.02502928 0.62938293]]]


In [23]:
print(arr.shape)

(3, 3, 3)


In [24]:
print(arr.size)

27


In [25]:
print(arr.dtype)

float64


In [26]:
# task2 : Array indexing and slicing

In [28]:
data = np.array([10,20,30,40,50,60,70,80,90])

In [29]:
data

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [31]:
print(data[:3])

[10 20 30]


In [32]:
print(data[::2])

[10 30 50 70 90]


In [33]:
print(data[1::2])

[20 40 60 80]


In [34]:
print(data[::-1])

[90 80 70 60 50 40 30 20 10]


In [35]:
# task 3 : Mathematical Operations

In [ ]:
# 1.creating two numpy arrays a and b

In [44]:
A = np.random.randint(1,21,size=(5))

In [45]:
A

array([ 6, 18, 19, 12,  8], dtype=int32)

In [46]:
B = np.random.randint(1,21,size=(5))

In [47]:
B

array([ 1, 17, 14,  1, 14], dtype=int32)

In [ ]:
# Some operations

In [48]:
A+B

array([ 7, 35, 33, 13, 22], dtype=int32)

In [49]:
A-B

array([ 5,  1,  5, 11, -6], dtype=int32)

In [50]:
A*B

array([  6, 306, 266,  12, 112], dtype=int32)

In [51]:
A/B 

array([ 6.        ,  1.05882353,  1.35714286, 12.        ,  0.57142857])

In [52]:
# dot product

In [53]:
dot_prod = np.dot(A,B)

In [54]:
print(dot_prod)

702


In [55]:
# Find the mean, median, standard deviation, and variance of
# array A.

In [56]:
print(np.mean(A))

12.6


In [57]:
print(np.median(A))

12.0


In [58]:
print(np.std(A))

5.2


In [59]:
print(np.var(A))

27.04


In [60]:
# max and min of B

In [62]:
B

array([ 1, 17, 14,  1, 14], dtype=int32)

In [61]:
print(np.max(B),np.argmax(B))

17 1


In [63]:
print(np.min(B),np.argmin(B))

1 0


In [64]:
# Reshaping and Transposing

In [65]:
arr = np.arange(1,13)

In [66]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [71]:
a2 = arr.reshape(4,3)
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [72]:
a3 = arr.reshape(2,2,3)
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [73]:
# Transpose
a2.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [75]:
print(a2.T.shape)

(3, 4)


In [76]:
# Boolean Masking and filtering

In [77]:
arr = np.random.randint(10,51,size=(15))

In [79]:
print(arr)

[15 22 16 16 39 15 12 48 25 18 18 36 22 48 49]


In [85]:
# Find all elements greater than 25.
# for el in arr:
#     if(el > 25):
#         print(el)
print(arr[arr > 25])

[39 48 36 48 49]


In [86]:
# o Replace all elements less than 30 with 0.
# for i in range(15):
#     if(arr[i] < 30):
#         arr[i] = 0
arr[arr < 30] = 0

In [87]:
print(arr)

[ 0  0  0  0 39  0  0 48  0  0  0 36  0 48 49]


In [88]:
#  Count the number of elements divisible by 5. 
# count = 0
# for el in arr:
#     if(el % 5 == 0):
#         count+=1
# print(count)

print(np.sum(arr % 5 == 0))

10


In [89]:
# Task 6: Working with Built-in Functions


In [92]:
#  Create an array of 10 equally spaced values between 0 and 1.
arr = np.linspace(0,1,10)

In [93]:
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [94]:
# Create an identity matrix of size 4x4.
mat = np.eye(4)

In [95]:
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [98]:
# Generate a 1D array of 20 random integers between 1 and 100,
# sort it, and find the 5 largest elements

arr = np.random.randint(1,101,size=(20))

In [99]:
print(arr)

[79 38 12 89 51 83 58  1 56 85 51 24 70 86 47  4 78 53 97 89]


In [100]:
sorted_arr = sorted(arr)

In [101]:
print(sorted_arr)

[np.int32(1), np.int32(4), np.int32(12), np.int32(24), np.int32(38), np.int32(47), np.int32(51), np.int32(51), np.int32(53), np.int32(56), np.int32(58), np.int32(70), np.int32(78), np.int32(79), np.int32(83), np.int32(85), np.int32(86), np.int32(89), np.int32(89), np.int32(97)]


In [102]:
print(sorted_arr[-5:])

[np.int32(85), np.int32(86), np.int32(89), np.int32(89), np.int32(97)]


In [103]:
# 

In [104]:
# Task 7 : Generic

In [105]:
import time

In [106]:
# generate two large random arrays of size (100, 100)
A = np.random.rand(100,100)
B = np.random.rand(100,100)

In [108]:
print(A)

[[0.30987177 0.0474473  0.17250631 ... 0.93726742 0.90193187 0.36157861]
 [0.7129233  0.24769354 0.98481941 ... 0.73366651 0.7163026  0.91904139]
 [0.55076447 0.20752647 0.52863061 ... 0.41175596 0.17038135 0.24951319]
 ...
 [0.33006343 0.95661449 0.52742416 ... 0.08372306 0.01126843 0.28682024]
 [0.43033404 0.14665782 0.10334459 ... 0.08728274 0.05817852 0.70575556]
 [0.30130193 0.09341135 0.06139384 ... 0.86372188 0.76189153 0.1400132 ]]


In [109]:
print(B)

[[0.52846292 0.78399843 0.17034563 ... 0.74549767 0.57525432 0.85209555]
 [0.28954912 0.2333315  0.88108301 ... 0.07152085 0.00554855 0.06858345]
 [0.795094   0.65023858 0.87329927 ... 0.80333544 0.74587445 0.34849097]
 ...
 [0.82714565 0.59468775 0.75528588 ... 0.49104637 0.88869063 0.03025794]
 [0.33856189 0.0214106  0.98222492 ... 0.93899368 0.26864375 0.77485065]
 [0.47849812 0.25791894 0.30712835 ... 0.65008522 0.16574022 0.62257301]]


In [110]:
start_time = time.time()

In [112]:
# perform matrix multiplication
result = np.dot(A,B)
print(result)

[[26.43075455 23.37329392 27.78986802 ... 28.30440654 24.92188464
  25.53625064]
 [24.57497316 20.1784952  27.33607209 ... 25.89991776 25.52784139
  26.27518476]
 [22.2485078  19.97825815 23.93764965 ... 23.25840439 23.31730857
  24.07956197]
 ...
 [24.72589671 22.85707619 28.62755995 ... 27.96620511 24.04610032
  26.36768819]
 [23.89160518 21.47577384 24.3402005  ... 25.17261491 21.6047776
  23.74552687]
 [26.79589729 21.54225779 27.75367004 ... 26.49879923 24.58441465
  27.69200745]]


In [114]:
# Finds the determinant and inverse of the resulting matrix (if
# possible).

try:
    det = np.linalg.det(result)
    print(det)
    if(det != 0):
        inverse = np.linalg.inv(result)
        print("Inverse calculated")
    else:
        print("Non- invertible")
except np.linalg.LinAlgError as e:
    print("Error:",e)

-3.046532121506468e+50
Inverse calculated


In [115]:
end_time = time.time()

In [116]:
print(f'time taken for all operations:{end_time-start_time}')

time taken for all operations:192.58266186714172
